[app]
GOOGLE_API_KEY = "AlzaSyAChjmc5zX-B3w85FVK7AZM7IOUSQcinY"
MONGODB_URI = "mongo+srv://joseaguero:glamor18@jraa.alsii83.mongodb.net/"
USER = "José Roberto Agüero Anchivilca"
COHERE_API_KEY = "4fiM9H8akndJ6dmPznajQdluKmBdXWNA9UOJknQ"

[b2]
B2_BUCKET_NAME = "JOSERAA"
B2_READ_KEY_ID = "0058c14771ecdd40000000004"
B2_READ_APPLICATION_KEY = "K005/0uBhyk+Op+/yhbCnJv50RLDdf4"
B2_WRITE_KEY_ID = "0058c14771ecdd40000000005"
B2_WRITE_APPLICATION_KEY = "K005MNFCJB2IXZL+w7j2AUtSTR+QiUA"
